language: go

go:
  - 1.9
  - master

matrix:
  allow_failures:
    - go: master
  fast_finish: true

notifications:
  email: false

before_script:
  - go get -t ./...
  - GO_FILES=$(find . -iname '*.go' -type f | grep -v /godogs/) # All the .go files, excluding vendor/
  - go get github.com/golang/lint/golint                        # Linter
  - go get github.com/fzipp/gocyclo
  - go get github.com/DATA-DOG/godog/cmd/godog

script:
  - test -z $(gofmt -s -l $GO_FILES)
  - go test -v -race ./...
  - cd godogs && godog
  - go vet ./...
  - gocyclo -over 3 $(echo $GO_FILES)
  - golint -set_exit_status $(go list ./...)
