language: go

go:
  - 1.9
  - master

matrix:
  allow_failures:
    - go: master
  fast_finish: true

notifications:
  email: false

before_script:
  - go get -t ./...
  - GO_FILES=$(find . -iname '*.go' -type f | grep -v /godogs/ | tr "\n" " ") # All the .go files, excluding vendor/
  - go get github.com/golang/lint/golint                        # Linter
  - go get github.com/fzipp/gocyclo
  - go get github.com/DATA-DOG/godog/cmd/godog
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls

script:
  - test -z $(gofmt -s -l $GO_FILES)
  - go test -v -covermode=atomic -coverprofile=main.coverprofile ./...
  - go vet -v ./...
  - gocyclo -over 4 $(echo $GO_FILES)
  - golint -set_exit_status $(go list ./...)
  - goveralls -coverprofile=main.coverprofile -service=travis-pro
  - cd godogs && godog
