version: 2
jobs:
  build:
    working_directory: /go/src/github.com/segurosfalabella/imperium-worker
    docker:
      - image: circleci/golang:1.9

    steps:
      - checkout

      - run: go get -t ./...
      - run: GO_FILES=$(find . -iname '*.go' -type f | grep -v /godogs/ | tr "\n" " ")
      - run: go get github.com/golang/lint/golint
      - run: go get github.com/fzipp/gocyclo
      - run: go get github.com/DATA-DOG/godog/cmd/godog

      - run: test -z $(gofmt -s -l $GO_FILES)
      - run: go test -v -race ./...
      - run: go test -race -coverprofile=coverage.txt -covermode=atomic ./...
      - run: go vet -v ./...
      - run: gocyclo -over 4 $(echo $GO_FILES)
      - run: golint -set_exit_status $(go list ./...)
      - run: cd godogs && godog && cd ..
      - run: ./build.sh
      # - run: docker build -t falabellacr/imperium-worker:c-${TRAVIS_BUILD_NUMBER} .
      # - run: docker push falabellacr/imperium-worker:c-${TRAVIS_BUILD_NUMBER}
